### PR TITLE
Build SDK with Bitcode enabled.

### PR DESCRIPTION
**Pull request by ninesharp**

### CODE REVIEW

**Comment by nosrak113** [comment]
And update the podspec and version? thanks

**Comment by nosrak113** [comment]
Still seeing the same error w/ this binary

**Comment by ninesharp** [comment]
Hi nosrak; were you able to use the binary directly, or still using pods?

**Comment by nosrak113** [comment]
Just pointed the pod to 
    pod 'TenjinSDK' , :git => 'https://github.com/ninesharp/tenjin-ios-sdk.git' 
and got 
     TenjinSDK:
    :commit: 562c8d1246c27518bbc42cc408e6808c6f3f2788
    :git: https://github.com/ninesharp/tenjin-ios-sdk.git

still no luck

**Comment by nosrak113** [comment]
have your tried
```
OTHER_CFLAGS="-fembed-bitcode"
```

**Comment by ninesharp** [comment]
Not yet, though the binary did have __bitcode and __llvm segments with ENABLE_BITCODE on. But will try that as well.

**Comment by ninesharp** [comment]
Alright, that binary is significantly larger (what I'd expect from actually embedding the bitcode). Give it a shot now.

**Comment by nosrak113** [comment]
Got it, and it works! Thanks for your help

**Comment by ninesharp** [comment]
Happy to help! Thanks for helping us keep up to date and using Tenjin. :)

**Pull request merged**
